name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: toolchain-install
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - name: toolchain
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - name: environment
        run: rustup target add thumbv7em-none-eabihf
      - name: x86_64
        run: cargo build --target x86_64-rust_os.json
      - name: bootimage
        run: cargo install bootimage
      - name: llvm
        run: rustup component add llvm-tools-preview
      - name: Build
        run: cargo build --target thumbv7em-none-eabihf --verbose
      - name: Run tests
        run: cargo test --verbose
