name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: qemu
        run: sudo apt install qemu
      - name: toolchain-install
        run: rustup toolchain install nightly-x86_64-unknown-linux-gnu
      - name: toolchain
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - name: environment
        run: rustup target add thumbv7em-none-eabihf
      - name: x86_64
        run: cargo build --target x86_64-rust_os.json
      - name: bootimage-install
        run: cargo install bootimage
      - name: llvm
        run: rustup component add llvm-tools-preview
      - name: bootimage
        run: cargo bootimage
      - name: debug
        run: ls /home/runner/work/rust-os/rust-os/target/x86_64-rust_os/debug/deps/
      - name: Run tests
        run: cargo run --verbose
